# Copyright ©khulnasoft-bot <info@khulnasoft.com>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/Deepsquads/meta/
github: [khulnasoft-bot, Deepsquads]
custom: https://deepsquads.github.io/donate/
liberapay: Deepsquads
open_collective: deepsquads
polar: Deepsquads
