# Copyright ©khulnasoft-bot <info@khulnasoft.com>
#
# SPDX-License-Identifier: CC0-1.0
#
# This file is maintained in https://github.com/Deepsquads/meta/

first-line-heading: false
line-length: false
html:
  allowed_elements: [a, img]
