#!/usr/bin/env python

# Copyright ©khulnasoft-bot <info@khulnasoft.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Simple wrapper to execute deepsquads-discovery commandline."""

import sys

import translation_finder.api

sys.exit(translation_finder.api.cli())
